export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const FETCH_COLLECTION_START = "FETCH_COLLECTION_START";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_COLLECTION_FAILED = "FETCH_COLLECTION_FAILED";

export const SET_PHOTO_DATA = 'SET_PHOTO_DATA'